tf.argmax가 잘 이해 안 되는데 테스트해보자.

In [1]:
import tensorflow as tf
import numpy as np

sess = tf.Session()
sess.run(tf.global_variables_initializer())

# 1차원 배열

In [2]:
arr = np.array([0, 0, 1])
print(arr.shape)

(3,)


In [3]:
sess.run(tf.argmax(arr, 0))

2

# 2차원 배열

In [43]:
arr = np.array([
                [0.1, 0.5, 0.4], 
                [0.2, 0.1, 0.6],
               ])
print(arr.shape)

(2, 3)


In [44]:
mx = sess.run(tf.argmax(arr, 0))
print(mx.shape)
mx

(3,)


array([1, 0, 1])

In [45]:
mx = sess.run(tf.argmax(arr, 1))
print(mx.shape)
mx

(2,)


array([1, 2])

# 3차원 배열

In [16]:
arr = np.array([
                [
                   [0.1, 0.3, 0.5, 0.1],
                   [0.3, 0.5, 0.1, 0.1],
                ],
                [
                   [0.5, 0.1, 0.3, 0.1],
                   [0.1, 0.3, 0.5, 0.1]
                ],
                [
                   [0.3, 0.5, 0.1, 0.1],
                   [0.5, 0.1, 0.3, 0.1]
                ],
                ])

print(arr.shape)

(3, 2, 4)


In [23]:
mx = sess.run(tf.argmax(arr, 0))
print(mx.shape)
mx

(2, 4)


array([[1, 2, 0, 0],
       [2, 0, 1, 0]])

In [24]:
mx = sess.run(tf.argmax(arr, 1))
print(mx.shape)
mx

(3, 4)


array([[1, 1, 0, 0],
       [0, 1, 1, 0],
       [1, 0, 1, 0]])

In [25]:
mx = sess.run(tf.argmax(arr, 2))
print(mx.shape)
mx

(3, 2)


array([[2, 1],
       [0, 2],
       [1, 0]])

# 4차원 배열

In [38]:
arr = np.array([
                [
                    [
                       [0.1, 0.3, 0.5, 0.1],
                       [0.3, 0.5, 0.1, 0.1],
                    ],
                    [
                       [0.5, 0.1, 0.3, 0.1],
                       [0.1, 0.3, 0.5, 0.1]
                    ],
                    [
                       [0.3, 0.5, 0.1, 0.1],
                       [0.5, 0.1, 0.3, 0.1]
                    ],
                ],
                [
                    [
                       [0.1, 0.9, 0.5, 0.1],
                       [0.3, 0.5, 0.1, 0.1],
                    ],
                    [
                       [0.5, 0.1, 0.9, 0.1],
                       [0.1, 0.3, 0.5, 0.1]
                    ],
                    [
                       [0.3, 0.5, 0.1, 0.1],
                       [0.5, 0.9, 0.3, 0.1]
                    ],
                ],
])

print(arr.shape)

(2, 3, 2, 4)


In [39]:
mx = sess.run(tf.argmax(arr, 0))
print(mx.shape)
mx

(3, 2, 4)


array([[[0, 1, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 1, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 1, 0, 0]]])

In [40]:
mx = sess.run(tf.argmax(arr, 1))
print(mx.shape)
mx

(2, 2, 4)


array([[[1, 2, 0, 0],
        [2, 0, 1, 0]],

       [[1, 0, 1, 0],
        [2, 2, 1, 0]]])

```
arr[i][j][k] = max_index(arr[i][0][j][k], arr[i][1][j][k], arr[i][2][j][k])
```

In [41]:
mx = sess.run(tf.argmax(arr, 2))
print(mx.shape)
mx

(2, 3, 4)


array([[[1, 1, 0, 0],
        [0, 1, 1, 0],
        [1, 0, 1, 0]],

       [[1, 0, 0, 0],
        [0, 1, 0, 0],
        [1, 1, 1, 0]]])

```
arr[i][j][k] = max_index(arr[i][j][0][k], arr[i][j][1][k])
```

In [42]:
mx = sess.run(tf.argmax(arr, 3))
print(mx.shape)
mx

(2, 3, 2)


array([[[2, 1],
        [0, 2],
        [1, 0]],

       [[1, 1],
        [2, 2],
        [1, 1]]])

```
arr[i][j][k] = max_index(arr[i][j][k][0], arr[i][j][k])
```