In [1]:
import tensorflow as tf
import numpy as np

In [2]:
sess = tf.Session()
sess.run(tf.global_variables_initializer())

In [3]:
X = tf.placeholder(tf.float32, [3, 3]) 
keep_prob = tf.placeholder(tf.float32)

W1 = tf.random_normal([3, 3], stddev=0.3)
L1 = tf.nn.relu(tf.matmul(X, W1))
L1_drop = tf.nn.dropout(L1, keep_prob)

data = np.array([[1., 2., 3.], [3., 4., 5.], [4.,5., 6.]])
L1, L1_drop = sess.run([L1, L1_drop], feed_dict={X: data, keep_prob:0.5})

print(L1)
print(L1_drop)

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
[[0.5123465  0.         0.26843268]
 [0.9196515  0.         0.7442491 ]
 [1.1233041  0.         0.98215723]]
[[1.024693   0.         0.53686535]
 [0.         0.         1.4884982 ]
 [2.2466083  0.         0.        ]]
